# Generated by Django 4.0 on 2024-06-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faceimage_user_delete_userdata_faceimage_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='uploadDate',
            field=models.DateTimeField(default='2024-06-10 17:15:17 PM'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createDate',
            field=models.DateTimeField(default='2024-06-10 17:15:17 PM'),
        ),
    ]
