# Generated by Django 4.0 on 2024-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_faceimage_uploaddate_alter_user_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='uploadDate',
            field=models.DateTimeField(default='2024-06-10 17:32:17'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createDate',
            field=models.DateTimeField(default='2024-06-10 17:32:17'),
        ),
    ]
