# Generated by Django 4.0 on 2024-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_faceimage_uploaddate_alter_user_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
