# Generated by Django 4.0 on 2024-06-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_faceimage_uploaddate_alter_user_createdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=45)),
                ('productName', models.CharField(max_length=255)),
            ],
        ),
    ]
