# Generated by Django 4.0 on 2024-06-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='names',
        ),
    ]
