# Generated by Django 4.0 on 2024-06-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='IP',
            field=models.CharField(max_length=20),
        ),
    ]
