# Generated by Django 4.0 on 2024-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_users_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('create_date', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
