# Generated by Django 4.0 on 2024-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_recommend_userdata_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='orgImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%M/%d'),
        ),
    ]
