# Generated by Django 4.0 on 2024-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_recommend_userdata_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='UUID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
