# Generated by Django 4.0 on 2024-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_userdata_age_alter_userdata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='orgImage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uploadDate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
