# Generated by Django 4.0 on 2024-06-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userdata_gender_alter_userdata_orgimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='UUID',
            field=models.CharField(default='', editable=False, max_length=255, unique=True),
        ),
    ]
