# Generated by Django 4.0 on 2024-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='UUID',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
