# Generated by Django 4.0 on 2024-06-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userdata_orgimage'),
        ('api', '0020_alter_userdata_uuid'),
    ]

    operations = [
    ]
