# Generated by Django 4.0 on 2024-06-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_userdata_orgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='orgImage',
            field=models.ImageField(upload_to='orgImg/'),
        ),
    ]
